//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCOADemoFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_User_Log
    {
        public int F_Id { get; set; }
        public string LoginName { get; set; }
        public string RealName { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public string Village { get; set; }
        public string OrgName { get; set; }
    }
}
