//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCOADemoFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_WeChatUser
    {
        public string F_Id { get; set; }
        public string WeChatName { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string Person_Id { get; set; }
        public string Phone { get; set; }
        public string UserType { get; set; }
        public string UserCompany { get; set; }
        public string CompanyTel { get; set; }
        public string UserJob { get; set; }
        public string Note { get; set; }
        public string IsAudit { get; set; }
        public string AuditResult { get; set; }
        public string AuditResultRemart { get; set; }
        public string Sha1OpenId { get; set; }
        public string OpenId { get; set; }
        public string Session_Key { get; set; }
        public string F_Description { get; set; }
        public Nullable<System.DateTime> F_CreatorTime { get; set; }
        public Nullable<System.DateTime> F_LastModifyTime { get; set; }
        public Nullable<System.DateTime> F_AuditTime { get; set; }
    }
}
