//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCOADemoFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Ballot
    {
        public string F_id { get; set; }
        public string Candidate { get; set; }
        public string Voters { get; set; }
        public Nullable<bool> F_DeleteMark { get; set; }
        public string F_EnabledMark { get; set; }
        public Nullable<System.DateTime> F_CreatorTime { get; set; }
        public string F_CreatorUserId { get; set; }
        public Nullable<System.DateTime> F_LastModifyTime { get; set; }
        public string F_LastModifyUserId { get; set; }
        public Nullable<System.DateTime> F_DeleteTime { get; set; }
        public string F_DeleteUserId { get; set; }
    }
}
