//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCOADemoFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_News
    {
        public string F_Id { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string NewsContent { get; set; }
        public string Abstract { get; set; }
        public Nullable<System.DateTime> ReleaseTime { get; set; }
        public string Channel { get; set; }
        public string URL { get; set; }
        public string Video { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<bool> F_DeleteMark { get; set; }
        public string F_EnabledMark { get; set; }
        public Nullable<System.DateTime> F_CreatorTime { get; set; }
        public string F_CreatorUserId { get; set; }
        public Nullable<System.DateTime> F_LastModifyTime { get; set; }
        public string F_LastModifyUserId { get; set; }
        public Nullable<System.DateTime> F_DeleteTime { get; set; }
        public string F_DeleteUserId { get; set; }
    }
}
