//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCOADemoFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PartyBuild
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string Person_ID { get; set; }
        public string Nation { get; set; }
        public string Birth { get; set; }
        public string NativePlace { get; set; }
        public string EDegree { get; set; }
        public string Aegree { get; set; }
        public string Etype { get; set; }
        public string AdmissionTime { get; set; }
        public string GraduationTime { get; set; }
        public string Partytime { get; set; }
        public string WorkTime { get; set; }
        public string StartPostTime { get; set; }
        public string Work_Unit { get; set; }
        public string Address { get; set; }
        public string Home_Phone { get; set; }
        public string Mobile_Phone { get; set; }
        public string Apolicestation { get; set; }
        public string PartyPlace { get; set; }
        public string Or_Unit { get; set; }
        public string Remark { get; set; }
        public string Zhen { get; set; }
        public string Qx { get; set; }
        public string Status { get; set; }
        public string PartyOldPlace { get; set; }
        public string NewPartyTime { get; set; }
        public string RollPartyTime { get; set; }
        public string HomeVillage { get; set; }
        public string Village { get; set; }
        public string Month_Money { get; set; }
        public string PartyOrganization { get; set; }
        public string byzd1 { get; set; }
        public string byzd2 { get; set; }
        public string byzd3 { get; set; }
        public string byzd4 { get; set; }
        public string QiTaBuChong { get; set; }
        public string CurrentAddress { get; set; }
        public string TransferType { get; set; }
        public string TransferDate { get; set; }
        public string TransferToBranch { get; set; }
        public string TransferCause { get; set; }
        public string OriginalPartyOrganization { get; set; }
        public string Category { get; set; }
        public string QiTaShenFen { get; set; }
        public string IsPartyMem { get; set; }
        public string PassWord { get; set; }
        public Nullable<bool> F_DeleteMark { get; set; }
        public Nullable<bool> F_EnabledMark { get; set; }
        public Nullable<System.DateTime> F_CreatorTime { get; set; }
        public string F_CreatorUserId { get; set; }
        public Nullable<System.DateTime> F_LastModifyTime { get; set; }
        public string F_LastModifyUserId { get; set; }
        public Nullable<System.DateTime> F_DeleteTime { get; set; }
        public string F_DeleteUserId { get; set; }
        public string F_Id { get; set; }
    }
}
