//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCOADemoFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PayResult
    {
        public string F_Id { get; set; }
        public string out_trade_no { get; set; }
        public string trade_no { get; set; }
        public string total_amount { get; set; }
        public string timestamp { get; set; }
        public string trade_type { get; set; }
    }
}
