//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCOADemoFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Tenant
    {
        public string F_Id { get; set; }
        public string F_DepartmentId { get; set; }
        public string F_SalesmanId { get; set; }
        public string F_ContractUnit { get; set; }
        public string F_ActualUnit { get; set; }
        public string F_LeaseContact { get; set; }
        public string F_LeaseContactPhone { get; set; }
        public string F_CertificateShare { get; set; }
        public string F_RegisteredAddress { get; set; }
        public string F_RegisteredCapital { get; set; }
        public Nullable<System.DateTime> F_EstablishDate { get; set; }
        public string F_ScopeBusiness { get; set; }
        public string F_IncreasingRent { get; set; }
        public string F_EnterpriseType { get; set; }
        public string F_ElectricityFees { get; set; }
        public string F_WaterFees { get; set; }
        public Nullable<System.DateTime> F_LastModifyTime { get; set; }
        public string F_LastModifyUserId { get; set; }
        public Nullable<System.DateTime> F_DeleteTime { get; set; }
        public string F_DeleteUserId { get; set; }
        public Nullable<bool> F_DeleteMark { get; set; }
        public Nullable<bool> F_EnabledMark { get; set; }
        public string F_Description { get; set; }
        public Nullable<System.DateTime> F_CreatorTime { get; set; }
        public string F_CreatorUserId { get; set; }
        public string F_UnitPrice { get; set; }
        public string F_TotalPrice { get; set; }
    }
}
