//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCOADemoFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TopicBack
    {
        public string F_id { get; set; }
        public string CardId { get; set; }
        public string UserName { get; set; }
        public string Org_Name { get; set; }
        public string TopicID { get; set; }
        public string Content { get; set; }
        public Nullable<int> States { get; set; }
        public Nullable<System.DateTime> CreatorTime { get; set; }
    }
}
