//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.R_Customer_Role = new HashSet<R_Customer_Role>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<R_Customer_Role> R_Customer_Role { get; set; }
    }
}
